### ISSUE TITLE
Pas de prise en compte des bonus d'équipemement

### ISSUE THREAD

**Issue by Ulty** [Ulty/ChroniquesContemporaines#14]
@stephaned68 
Dans une partie vide, créer un nouveau personnage, lui ajouter un équipement avec dans les propriétés `DEF:+2`. Cocher la case Équipement porté. Le bonus n'est pas reporté dans les caractéristiques.

En regardant la console, j'ai plein d'erreurs du style

jquery-1.9.1.js:6063 The specified value "@{CHA}" cannot be parsed, or is out of range.
(anonymous) @ jquery-1.9.1.js:6063
access @ jquery-1.9.1.js:852
html @ jquery-1.9.1.js:6038
render @ app.js?1587473048:566
showDialog @ app.js?1587473048:566
(anonymous) @ app.js?1587473048:574
dispatch @ jquery-1.9.1.js:3074
elemData.handle @ jquery-1.9.1.js:2750
sentryWrapped @ bundle.min.js:2
jquery-1.9.1.js:6063 The specified value "@{ATKPSI}" cannot be parsed, or is out of range.
(anonymous) @ jquery-1.9.1.js:6063
access @ jquery-1.9.1.js:852
html @ jquery-1.9.1.js:6038
render @ app.js?1587473048:566
showDialog @ app.js?1587473048:566
(anonymous) @ app.js?1587473048:574
dispatch @ jquery-1.9.1.js:3074
elemData.handle @ jquery-1.9.1.js:2750
sentryWrapped @ bundle.min.js:2
jquery-1.9.1.js:6063 The specified value "10+@{DEFPSI_CARAC}+@{DEFPSI_ATK}+@{DEFPSI_DIV}" cannot be parsed, or is out of range.
(anonymous) @ jquery-1.9.1.js:6063
access @ jquery-1.9.1.js:852
html @ jquery-1.9.1.js:6038
render @ app.js?1587473048:566
showDialog @ app.js?1587473048:566
(anonymous) @ app.js?1587473048:574
dispatch @ jquery-1.9.1.js:3074
elemData.handle @ jquery-1.9.1.js:2750
sentryWrapped @ bundle.min.js:2
jquery-1.9.1.js:6063 The specified value "@{FOR_BUFF}" cannot be parsed, or is out of range.
(anonymous) @ jquery-1.9.1.js:6063
access @ jquery-1.9.1.js:852
html @ jquery-1.9.1.js:6038
render @ app.js?1587473048:566
showDialog @ app.js?1587473048:566
(anonymous) @ app.js?1587473048:574
dispatch @ jquery-1.9.1.js:3074
elemData.handle @ jquery-1.9.1.js:2750
sentryWrapped @ bundle.min.js:2
jquery-1.9.1.js:6063 The specified value "@{DEX_BUFF}" cannot be parsed, or is out of range.
(anonymous) @ jquery-1.9.1.js:6063
access @ jquery-1.9.1.js:852
html @ jquery-1.9.1.js:6038
render @ app.js?1587473048:566
showDialog @ app.js?1587473048:566
(anonymous) @ app.js?1587473048:574
dispatch @ jquery-1.9.1.js:3074
elemData.handle @ jquery-1.9.1.js:2750
sentryWrapped @ bundle.min.js:2
jquery-1.9.1.js:6063 The specified value "@{CON_BUFF}" cannot be parsed, or is out of range.
(anonymous) @ jquery-1.9.1.js:6063
access @ jquery-1.9.1.js:852
html @ jquery-1.9.1.js:6038
render @ app.js?1587473048:566
showDialog @ app.js?1587473048:566
(anonymous) @ app.js?1587473048:574
dispatch @ jquery-1.9.1.js:3074
elemData.handle @ jquery-1.9.1.js:2750
sentryWrapped @ bundle.min.js:2
jquery-1.9.1.js:6063 The specified value "@{INT_BUFF}" cannot be parsed, or is out of range.
(anonymous) @ jquery-1.9.1.js:6063
access @ jquery-1.9.1.js:852
html @ jquery-1.9.1.js:6038
render @ app.js?1587473048:566
showDialog @ app.js?1587473048:566
(anonymous) @ app.js?1587473048:574
dispatch @ jquery-1.9.1.js:3074
elemData.handle @ jquery-1.9.1.js:2750
sentryWrapped @ bundle.min.js:2
jquery-1.9.1.js:6063 The specified value "@{PER_BUFF}" cannot be parsed, or is out of range.
(anonymous) @ jquery-1.9.1.js:6063
access @ jquery-1.9.1.js:852
html @ jquery-1.9.1.js:6038
render @ app.js?1587473048:566
showDialog @ app.js?1587473048:566
(anonymous) @ app.js?1587473048:574
dispatch @ jquery-1.9.1.js:3074
elemData.handle @ jquery-1.9.1.js:2750
sentryWrapped @ bundle.min.js:2
jquery-1.9.1.js:6063 The specified value "@{CHA_BUFF}" cannot be parsed, or is out of range.
(anonymous) @ jquery-1.9.1.js:6063
access @ jquery-1.9.1.js:852
html @ jquery-1.9.1.js:6038
render @ app.js?1587473048:566
showDialog @ app.js?1587473048:566
(anonymous) @ app.js?1587473048:574
dispatch @ jquery-1.9.1.js:3074
elemData.handle @ jquery-1.9.1.js:2750
sentryWrapped @ bundle.min.js:2
jquery-1.9.1.js:6063 The specified value "@{ATKCAC_BUFF}" cannot be parsed, or is out of range.
(anonymous) @ jquery-1.9.1.js:6063
access @ jquery-1.9.1.js:852
html @ jquery-1.9.1.js:6038
render @ app.js?1587473048:566
showDialog @ app.js?1587473048:566
(anonymous) @ app.js?1587473048:574
dispatch @ jquery-1.9.1.js:3074
elemData.handle @ jquery-1.9.1.js:2750
sentryWrapped @ bundle.min.js:2
jquery-1.9.1.js:6063 The specified value "@{ATKTIR_BUFF}" cannot be parsed, or is out of range.
(anonymous) @ jquery-1.9.1.js:6063
access @ jquery-1.9.1.js:852
html @ jquery-1.9.1.js:6038
render @ app.js?1587473048:566
showDialog @ app.js?1587473048:566
(anonymous) @ app.js?1587473048:574
dispatch @ jquery-1.9.1.js:3074
elemData.handle @ jquery-1.9.1.js:2750
sentryWrapped @ bundle.min.js:2
jquery-1.9.1.js:6063 The specified value "@{ATKMEN_BUFF}" cannot be parsed, or is out of range.
(anonymous) @ jquery-1.9.1.js:6063
access @ jquery-1.9.1.js:852
html @ jquery-1.9.1.js:6038
render @ app.js?1587473048:566
showDialog @ app.js?1587473048:566
(anonymous) @ app.js?1587473048:574
dispatch @ jquery-1.9.1.js:3074
elemData.handle @ jquery-1.9.1.js:2750
sentryWrapped @ bundle.min.js:2
jquery-1.9.1.js:6063 The specified value "@{ATKPIL_BUFF}" cannot be parsed, or is out of range.
(anonymous) @ jquery-1.9.1.js:6063
access @ jquery-1.9.1.js:852
html @ jquery-1.9.1.js:6038
render @ app.js?1587473048:566
showDialog @ app.js?1587473048:566
(anonymous) @ app.js?1587473048:574
dispatch @ jquery-1.9.1.js:3074
elemData.handle @ jquery-1.9.1.js:2750
sentryWrapped @ bundle.min.js:2
jquery-1.9.1.js:6063 The specified value "@{ATKMAG_BUFF}" cannot be parsed, or is out of range.
(anonymous) @ jquery-1.9.1.js:6063
access @ jquery-1.9.1.js:852
html @ jquery-1.9.1.js:6038
render @ app.js?1587473048:566
showDialog @ app.js?1587473048:566
(anonymous) @ app.js?1587473048:574
dispatch @ jquery-1.9.1.js:3074
elemData.handle @ jquery-1.9.1.js:2750
sentryWrapped @ bundle.min.js:2
jquery-1.9.1.js:6063 The specified value "@{INIT_BUFF}" cannot be parsed, or is out of range.
(anonymous) @ jquery-1.9.1.js:6063
access @ jquery-1.9.1.js:852
html @ jquery-1.9.1.js:6038
render @ app.js?1587473048:566
showDialog @ app.js?1587473048:566
(anonymous) @ app.js?1587473048:574
dispatch @ jquery-1.9.1.js:3074
elemData.handle @ jquery-1.9.1.js:2750
sentryWrapped @ bundle.min.js:2
jquery-1.9.1.js:6063 The specified value "@{DEF_BUFF}" cannot be parsed, or is out of range.
(anonymous) @ jquery-1.9.1.js:6063
access @ jquery-1.9.1.js:852
html @ jquery-1.9.1.js:6038
render @ app.js?1587473048:566
showDialog @ app.js?1587473048:566
(anonymous) @ app.js?1587473048:574
dispatch @ jquery-1.9.1.js:3074
elemData.handle @ jquery-1.9.1.js:2750
sentryWrapped @ bundle.min.js:2
jquery-1.9.1.js:6063 The specified value "@{PV_BUFF}" cannot be parsed, or is out of range.
(anonymous) @ jquery-1.9.1.js:6063
access @ jquery-1.9.1.js:852
html @ jquery-1.9.1.js:6038
render @ app.js?1587473048:566
showDialog @ app.js?1587473048:566
(anonymous) @ app.js?1587473048:574
dispatch @ jquery-1.9.1.js:3074
elemData.handle @ jquery-1.9.1.js:2750
sentryWrapped @ bundle.min.js:2
jquery-1.9.1.js:6063 The specified value "@{DEFV_BASE}+@{DEFV_DEX}" cannot be parsed, or is out of range.

**Comment by stephaned68** [comment]
@Ulty 
Oui, j'ai vu ces pages d'erreurs, je ne sais vraiment pas d'où ça vient, mais comme ce sont les champs auto-calc de la fiche, je me demande si ce n'est pas justement la source des problèmes de liaison entre certains attributs et les barres de tokens que nous avons depuis une semaine
Pour le problème sur les armures, je viens de le corriger. En ajoutant la possibilité de créer/supprimer une ligne d'attaque liée à un équipement, j'ai cassé ce que j'avais fait précédemment sur l'armure
Par contre, je me rends compte que je n'ai pas prévu le cas de protection dont les DEF se cumuleraient -- Je ne crois pas que ce soit prévu, ni dans COC ni dans CG, et il n'y a pas de boucliers non plus ;) Veux-tu que je le rajoute, histoire de te faciliter la vie le jour où tu récupéreras le code pour COF ? Encore que, il y a un champ spécial pour le bouclier sur la fiche COF. Dis-moi ce que tu en penses.
Merci pour ton aide en tout cas :)

**Comment by Ulty** [comment]
Tu as raison, j'ai les mêmes sur COFantasy, et je me disais que j'allais peut-être supprimer ça à terme pour les remplacer par des calculs avec le script.

Bref, pour revenir à la fiche COC, je suis content que tu aies pu corriger le bug, c'est vraiment énorme ce que tu as fait. Pour la gestion des armures et boucliers, je me pose des questions : quelle est la sémantique de la case à cocher Équipement porté ? Vu l'effet sur l'encombrement, j'imagine que c'est pour savoir si on a l'équipement sur soi ou si on l'a laissé à la maison ? Dans ce cas, on ne peut pas utiliser directement cela pour l'armure (ou le bouclier), puisqu'on doit savoir en plus si on a enfilé l'armure (et pour le bouclier si on le tient en main ou dans le dos).

Est-ce qu'on pourrait imaginer que le champ armure devienne read-only, et il affiche le nom du premier équipement avec dans ses carcactéristiques le mot clé `armure` ? Le mieux serait d'avoir un menu déroulant parmis tous ces équipement, mais je ne sais pas si c'est possible avec les contraintes de character sheet... Si oui, on pourrait faire pareil pour le bouclier en fantasy. Et du coup l'armure augmenterait l'encombrement quand on l'a sur soit, mais n'apporterait les bonus de DEF, malus de DEX, bonus de RD, que si elle est portée, ce qui correspondrait à la case dans l'onglet caractéristiques.

**Comment by stephaned68** [comment]
Hello

Oui, en effet, la case "Equipement porté" permet de faire la différence entre quelque chose que tu possèdes mais que tu as laissé dans ton appartement/conapt/planque et quelque chose que tu portes sur toi, qui est donc pris en compte dans le calcul de l'encombrement, sachant qu'il faut cocher la case sur l'onglet Configuration pour que le résultat de ce calcul ait éventuellement des effets préjudiciables sur les capacités selon le seuil d'encombrement atteint (FOR, FOR x 2, FOR x 3)

Pour un menu déroulant des armures trouvées dans la liste des équipements, je ne pense pas que ce soit possible, il faudrait créer dynamiquement des éléments select et option et les insérer dans le DOM, or on n'y a pas accès dans les sheet-workers. 

Par contre, la synchro entre les deux cases "Porté" (celle de la liste d'équipement et celle de la DEF) n'est pas bidirectionnelle. Quand tu changes côté équipement, ça change côté DEF, mais pas l'inverse. Ca suffirait peut-être à faire le distinguo ?

**Comment by stephaned68** [comment]
@Ulty 
Je n'ai pas la possibilité de modifier l'état de tes Issues pour indiquer a minima quand elles sont réglées ;)

**Comment by Ulty** [comment]
Je n'avais pas vu ça. Il faudra que je trouve comment changer ça.
