### ISSUE TITLE
Def psi, attaque psi, points de tensions, niveau de vie pour coc-x

### ISSUE THREAD

**Issue by slipenbois** [Ulty/ChroniquesContemporaines#7]
Hello, 

serait il possible de rajouter 
- Def Psi : 10 +Bonus + Mod de CHA + score d'attaque psi
- Attaque Psi: Bonus + Mod d' INT
- Points  de tension (PT) 
- Niveau de vie (Quelque part dans équipement)

Cdlt

**Comment by stephaned68** [comment]
Hello @slipenbois

Quelques pistes de réponse à certaines de tes question (ici et sur le forum BBe)

- Pour les points de tension, tu peux utiliser la liste personnalisée des autres ressources : 
![image](https://user-images.githubusercontent.com/11362419/51460434-b8baf380-1d5b-11e9-8e76-1efc305f1cc1.png)

- Pour le niveau de vie, tu peux utiliser la liste personnalisée des traits : 
![image](https://user-images.githubusercontent.com/11362419/51460771-b4430a80-1d5c-11e9-88ec-da0b7e7e9cfe.png)

- Pour les DM supplémentaires (qui en principe ne sont pas doublés en cas de critique), le champ Spécial de la liste des armes est là pour ça : 
![image](https://user-images.githubusercontent.com/11362419/51460619-41399400-1d5c-11e9-9a18-bb8967157150.png)

Bien à toi ;)

**Comment by Ulty** [comment]
Ça me semble réglé, non ?

**Comment by stephaned68** [comment]
Oui, je suis en train de ré-intégrer dans COC les dernières modifs pour CG qui résolvent la plupart des demandes de @slipenbois 
J'ai aussi ajouté les spécificités Menace-X en bas de l'onglet Configuration : 
![screenshot-app roll20 net-2019 02 11-10-41-11](https://user-images.githubusercontent.com/11362419/52555362-c529ed80-2de9-11e9-80f7-dee71a33e1d7.png)
Merci qui ? ;)
